spring.application.name=EasyShop
server.port=0 

##database properties
spring.datasource.url=jdbc:postgresql://localhost:5432/easyshopdata
spring.datasource.username=postgres
spring.datasource.password=25061314
spring.datasource.driver-class-name=org.postgresql.Driver
##Jpa
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view = false
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
#Auto Logout
AUTO_LOGOUT_TIME=10m
server.servlet.session.timeout=${AUTO_LOGOUT_TIME}